#ifndef NUMERIC_REPLIES_HPP
#define NUMERIC_REPLIES_HPP

#define RPL_TOPIC 332
#define RPL_NOTOPIC 331
#define RPL_NAMREPLY "353"
#define RPL_ENDOFNAMES "366"
#define ERR_NOTREGISTERED 451
#define ERR_NEEDMOREPARAMS 461
#define ERR_TOOMANYMATCHES
#define RPL_LISTSTART " 321 "
#define RPL_LIST " 322 "
#define RPL_LISTEND " 323 "
#define RPL_VERSION " 351 "
#define ERR_NOSUCHSERVER " 402 "

#endif
