#ifndef NUMERIC_REPLIES_HPP
#define NUMERIC_REPLIES_HPP

#define RPL_TOPIC 332
#define RPL_NOTOPIC 331
#define RPL_NAMREPLY "353"
#define RPL_ENDOFNAMES "366"
#define ERR_NOTREGISTERED 451
#define ERR_NEEDMOREPARAMS 461
#define ERR_INVITEONLYCHAN " 473 "

#endif
