#ifndef NUMERIC_REPLIES_HPP
#define NUMERIC_REPLIES_HPP

#define RPL_WELCOME				"001"
#define RPL_AWAY				"301"
#define	RPL_UNAWAY				"305"
#define RPL_NOWAWAY				"306"
#define RPL_NOTOPIC				331
#define RPL_TOPIC				332
#define RPL_LISTSTART " 321 "
#define RPL_LIST " 322 "
#define RPL_LISTEND " 323 "
#define RPL_TOPIC 332
#define RPL_NOTOPIC 331
#define RPL_NAMREPLY "353"
#define RPL_ENDOFNAMES "366"
#define ERR_CHANNELISFULL " 471 "
#define RPL_VERSION " 351 "
#define RPL_NAMREPLY			"353"
#define RPL_ENDOFNAMES			"366"
#define ERR_TOOMANYMATCHES
#define ERR_NOSUCHNICK			"401"
#define ERR_NOSUCHSERVER " 402 "
#define ERR_CANNOTSENDTOCHAN	"404"
#define ERR_TOOMANYTARGETS		"407"
#define ERR_NORECIPIENT			"411"
#define ERR_NOTEXTTOSEND		"412"
#define ERR_NOTONCHANNEL		" 442 "
#define ERR_USERONCHANNEL		" 443 "
#define ERR_NOTREGISTERED		451
#define ERR_NEEDMOREPARAMS		" 461 "
#define ERR_INVITEONLYCHAN		" 473 "
#define ERR_BADCHANNELKEY		" 475 "

#endif
